import type { StoreCategory, StoreCollection, StoreProduct } from "@/types/store";

export const categories: StoreCategory[] = [
  {
    id: "cat-images",
    name: "Imagenes religiosas",
    slug: "imagenes-religiosas",
    description: "Esculturas en resina epoxi para contemplar, regalar y habitar.",
  },
  {
    id: "cat-jewelry",
    name: "Joyeria religiosa",
    slug: "joyeria-religiosa",
    description: "Medallas, dijes y piezas devocionales con lenguaje contemporaneo.",
  },
];

export const collections: StoreCollection[] = [
  {
    id: "col-gifts",
    name: "Regalos con sentido",
    slug: "regalos-con-sentido",
    description: "Piezas para nacimiento, bautismo, celebracion o acompanamiento espiritual.",
    featured: true,
  },
  {
    id: "col-medals",
    name: "Medallas significativas",
    slug: "medallas-significativas",
    description: "Joyeria devocional pensada para acompanar la vida cotidiana.",
    featured: true,
  },
  {
    id: "col-home",
    name: "Presencia en el hogar",
    slug: "presencia-en-el-hogar",
    description: "Imagenes y objetos para espacios de calma y contemplacion.",
  },
];

export const devotions = ["Virgen Milagrosa", "San Benito", "Virgen de Lourdes", "Sagrada Familia"];
export const materials = ["Plata", "Plata y oro", "Plata + oro + esmalte", "Resina epoxi"];

export const products: StoreProduct[] = [
  {
    id: "prod-1",
    name: "Virgen de la Dulce Espera",
    slug: "virgen-dulce-espera-resina",
    subtitle: "Imagen en resina epoxi",
    description:
      "Pieza de presencia calma, pensada para acompanar espacios de contemplacion y momentos de regalo significativo. La superficie satinada y el gesto sereno ponen el foco en el volumen y la cercania del objeto.",
    line: "RESINA_EPOXI",
    sku: "AM-IMG-001",
    regularPrice: 185000,
    transferPrice: 166500,
    stock: 6,
    installmentsText: "Hasta 6 cuotas sin interes segun promocion vigente.",
    dimensions: "28 x 12 x 10 cm",
    weightGrams: 1300,
    careInstructions: "Limpiar con pano seco. Evitar abrasivos y sol directo prolongado.",
    categories: ["Imagenes religiosas"],
    collections: ["Regalos con sentido", "Presencia en el hogar"],
    materials: ["Resina epoxi"],
    devotions: ["Virgen de la Dulce Espera"],
    featured: true,
    tags: ["destacado", "nuevo"],
    images: [
      { url: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80", alt: "Imagen escultorica sobria en resina", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80", alt: "Detalle de materialidad y volumen" },
    ],
    variants: [],
  },
  {
    id: "prod-2",
    name: "Sagrada Familia en resina",
    slug: "sagrada-familia-resina",
    subtitle: "Escultura devocional",
    description:
      "Una lectura contemporanea de la Sagrada Familia, con proporciones limpias y una terminacion noble. Pensada para celebraciones familiares, nacimientos y regalos de profunda carga simbolica.",
    line: "RESINA_EPOXI",
    sku: "AM-IMG-002",
    regularPrice: 209000,
    transferPrice: 188100,
    stock: 4,
    installmentsText: "Hasta 6 cuotas sin interes segun promocion vigente.",
    dimensions: "30 x 14 x 12 cm",
    weightGrams: 1450,
    careInstructions: "Guardar protegida al trasladar. Limpiar con pano seco.",
    categories: ["Imagenes religiosas"],
    collections: ["Regalos con sentido"],
    materials: ["Resina epoxi"],
    devotions: ["Sagrada Familia"],
    featured: true,
    tags: ["destacado"],
    images: [
      { url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&q=80", alt: "Escultura clara y sobria", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=1200&q=80", alt: "Pieza fotografiada con luz suave" },
    ],
    variants: [],
  },
  {
    id: "prod-3",
    name: "Virgen de Lourdes en resina",
    slug: "virgen-lourdes-resina",
    subtitle: "Imagen vertical en resina epoxi",
    description:
      "Imagen de presencia limpia y vertical, con una lectura cuidada de la silueta y una terminacion serena para espacios de oracion o interiorismo contemplativo.",
    line: "RESINA_EPOXI",
    sku: "AM-IMG-003",
    regularPrice: 178000,
    transferPrice: 160200,
    stock: 5,
    installmentsText: "Hasta 6 cuotas sin interes segun promocion vigente.",
    dimensions: "26 x 11 x 9 cm",
    weightGrams: 1180,
    careInstructions: "No usar abrasivos ni exponer a humedad intensa.",
    categories: ["Imagenes religiosas"],
    collections: ["Presencia en el hogar"],
    materials: ["Resina epoxi"],
    devotions: ["Virgen de Lourdes"],
    featured: true,
    tags: ["nuevo"],
    images: [
      { url: "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80", alt: "Imagen de estilo editorial", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1482160549825-59d1b23cb208?auto=format&fit=crop&w=1200&q=80", alt: "Detalle de formas y textura" },
    ],
    variants: [],
  },
  {
    id: "prod-4",
    name: "Medalla Virgen Milagrosa oval",
    slug: "medalla-virgen-milagrosa-oval",
    subtitle: "Joyeria religiosa",
    description:
      "Una medalla de lectura delicada y precisa, pensada para acompanar la vida cotidiana desde una sensibilidad mas refinada que devocional. Ideal para regalo de bautismo, confirmacion o uso diario.",
    line: "JOYERIA",
    sku: "AM-JOY-001",
    regularPrice: 92000,
    transferPrice: 82800,
    stock: 14,
    installmentsText: "Hasta 3 cuotas sin interes con Mercado Pago.",
    dimensions: "2.2 x 1.6 cm",
    weightGrams: 12,
    careInstructions: "Guardar seca y evitar perfumes directos.",
    categories: ["Joyeria religiosa"],
    collections: ["Regalos con sentido", "Medallas significativas"],
    materials: ["Plata", "Plata y oro", "Plata + oro + esmalte"],
    devotions: ["Virgen Milagrosa"],
    featured: true,
    tags: ["destacado", "descuento transferencia"],
    images: [
      { url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1200&q=80", alt: "Medalla oval religiosa", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1617038220319-53d3e9f0a67d?auto=format&fit=crop&w=1200&q=80", alt: "Detalle de joyeria religiosa" },
    ],
    variants: [
      { id: "var-41", name: "Plata", sku: "AM-JOY-001-PL", regularPrice: 92000, transferPrice: 82800, stock: 8, material: "Plata", devotion: "Virgen Milagrosa", isDefault: true },
      { id: "var-42", name: "Plata y oro", sku: "AM-JOY-001-PO", regularPrice: 124000, transferPrice: 111600, stock: 4, material: "Plata y oro", devotion: "Virgen Milagrosa" },
      { id: "var-43", name: "Plata + oro + esmalte", sku: "AM-JOY-001-PGE", regularPrice: 141000, transferPrice: 126900, stock: 2, material: "Plata + oro + esmalte", devotion: "Virgen Milagrosa" },
    ],
  },
  {
    id: "prod-5",
    name: "Medalla San Benito circular",
    slug: "medalla-san-benito-circular",
    subtitle: "Medalla de mayor presencia",
    description:
      "Pieza de mayor presencia y excelente lectura simbolica. Conserva el espesor material y el equilibrio formal que necesita una joya de uso cotidiano con sentido.",
    line: "JOYERIA",
    sku: "AM-JOY-002",
    regularPrice: 98000,
    transferPrice: 88200,
    stock: 12,
    installmentsText: "Hasta 3 cuotas sin interes con Mercado Pago.",
    dimensions: "2.5 x 2.5 cm",
    weightGrams: 15,
    careInstructions: "Evitar golpes y contacto con productos abrasivos.",
    categories: ["Joyeria religiosa"],
    collections: ["Medallas significativas"],
    materials: ["Plata", "Plata y oro"],
    devotions: ["San Benito"],
    featured: true,
    tags: ["destacado"],
    images: [
      { url: "https://images.unsplash.com/photo-1617038220319-f0dbd3f9d3b3?auto=format&fit=crop&w=1200&q=80", alt: "Medalla circular de San Benito", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80", alt: "Joyeria fotografiada con fondo claro" },
    ],
    variants: [
      { id: "var-51", name: "Plata", sku: "AM-JOY-002-PL", regularPrice: 98000, transferPrice: 88200, stock: 9, material: "Plata", devotion: "San Benito", isDefault: true },
      { id: "var-52", name: "Plata y oro", sku: "AM-JOY-002-PO", regularPrice: 129000, transferPrice: 116100, stock: 3, material: "Plata y oro", devotion: "San Benito" },
    ],
  },
  {
    id: "prod-6",
    name: "Dije Cruz pequena con oro",
    slug: "dije-cruz-pequena-oro",
    subtitle: "Pieza de uso cotidiano",
    description:
      "Un dije pequeno, silencioso y elegante, pensado para quienes buscan una presencia espiritual cotidiana con una lectura visual contemporanea y simple.",
    line: "JOYERIA",
    sku: "AM-JOY-003",
    regularPrice: 76000,
    transferPrice: 68400,
    stock: 6,
    installmentsText: "Hasta 3 cuotas sin interes con Mercado Pago.",
    dimensions: "1.8 x 1.1 cm",
    weightGrams: 8,
    careInstructions: "Guardar en estuche individual y evitar humedad.",
    categories: ["Joyeria religiosa"],
    collections: ["Regalos con sentido"],
    materials: ["Plata y oro"],
    devotions: [],
    tags: ["descuento transferencia"],
    images: [
      { url: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1200&q=80", alt: "Dije pequeno con terminacion cuidada", isPrimary: true },
    ],
    variants: [
      { id: "var-61", name: "Plata y oro", sku: "AM-JOY-003-PO", regularPrice: 76000, transferPrice: 68400, stock: 6, material: "Plata y oro", isDefault: true },
    ],
  },
];
